[project]
name = "nd0277-data-engineering-with-microsoft-azure-project-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.13.0",
    "ty>=0.0.1a20",
]
